# Generated by Django 2.1.1 on 2019-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='to_loc_city',
            field=models.TextField(default=''),
        ),
    ]
